---

- hosts: all
  gather_facts: yes

- name: configuring HAproxy loadbalancer
  hosts: HAproxy
  become: yes
  tasks:
    - name: Installing HAproxy
      apt:
        name: haproxy
        state: present
        update_cache: true
    - name: gather facts
      setup:
        filter: ansible_default_ipv4.address
  
    - name: copy files haproxy.cfg
      template:
        src: haproxy.cfg
        dest: "/etc/haproxy/haproxy.cfg"
    - name: run Haproxy
      service:
        name: haproxy
        state: restarted




- hosts: webservers
  become: yes
  tasks:
    - name: install pip
      apt:
        name: python3-pip
        state: present
    - name: install flask
      pip:
        executable: pip3
        name: flask
        state: latest
    - name: copy app.py to webservers
      template:
        src: "app.py"
        dest: "/home"
    - name: start flask
      shell: |
         export FLASK_APP=/home/app.py
         export FLASK_RUN_HOST=0.0.0.0
         export FLASK_RUN_PORT=8080
         flask run&
      
