---

- hosts: all
  gather_facts: yes

- name: configuring HAproxy loadbalancer
  hosts: HAproxy
  become: yes
  tasks:
    - name: Installing HAproxy
      apt:
        name: haproxy
        state: present
        update_cache: true